version: "3.7"

services:
  treetool_apache:
    build: 
      context: ./bin/apache
      dockerfile: Dockerfile
      args:
        developer_uid: ${APACHE_DEVELOPER_UID}
        developer_name: ${USER}
    container_name: treetool_apache
    restart: 'on-failure'
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ~/.ssh:/home/${USER}/.ssh
      - ~/.gitconfig:/home/${USER}/.gitconfig
      - ${APACHE_DOCUMENT_ROOT}:/var/www/html/webapp
      - ${PHP_CONFIG_INI}:/usr/local/etc/php/php.ini
      - ${APACHE_CONFIG_DIR}/sites-enabled:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
    environment:
      APACHE_RUN_USER: ${USER}
      APACHE_RUN_GROUP: ${USER}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
      XDEBUG_CONFIG: "${XDEBUG_REMOTE_ENABLE} ${XDEBUG_REMOTE_HOST} ${XDEBUG_REMOTE_PORT} ${XDEBUG_IDEKEY}"
      TZ: ${TIME_ZONE}
    user: ${USER}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    networks:
      - treetool_network

networks:
  treetool_network:
