#!/bin/bash

ENV_FILE=.env

STOP="docker-compose down"
COMPOSE="docker-compose up -d > ./logs/docker.log";

if [[ -f "$ENV_FILE" ]]; then
  export $(cat "$ENV_FILE" | xargs)
else
  echo "File .env not exists! Docker need this file!"
  exit;
fi

eval ${STOP}
eval ${COMPOSE}

docker exec -it treetool_apache bash